create table appointment
(
    id           bigint generated by default as identity
        primary key,
    all_day      boolean not null,
    dietitian_id bigint,
    end_date     timestamp,
    start_date   timestamp,
    status       varchar(255),
    title        varchar(255),
    user_id      bigint
);